spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev                   #开发环境
  application:
    name: springcloud-service-config-dev
    
---
spring:
  profiles: test                  #测试环境
  application:
    name: springcloud-service-config-test

