spring:
  ##数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/deao?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true




# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.deao
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mapping/*/*.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis-config.xml
# 日志配置
logging:
  level:
    com.deao: trace
    org.springframework: WARN
    org.spring.springboot.dao: debug

#server.context-path=/sc-paej-system
#
#spring.datasource.url=jdbc:mysql://localhost:3306/deao?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=123456
#/libaba.druid.pool.DruidDataSource
#
#spring.datasource.initialSize=5
#spring.datasource.minIdle=5
#spring.datasource.maxActive=20
#spring.datasource.maxWait=60000
#spring.datasource.timeBetweenEvictionRunsMillis=60000
#spring.datasource.minEvictableIdleTimeMillis=300000
#spring.datasource.validationQuery=SELECT 1 FROM DUAL
#spring.datasource.testWhileIdle=true
#spring.datasource.testOnBorrow=false
#spring.datasource.testOnReturn=false
#spring.datasource.filters=stat,wall,log4j
#spring.datasource.logSlowSql=true
#
#mybatis.mapper-locations=classpath:mapping/*/*.xml
#configLocation=classpath:mybatis-config.xml
#
#spring.redis.host=127.0.0.1
#spring.redis.port=6379
#spring.redis.password=
#
#mybatis_redis_cache=600000
#shiro_redis_cache=600000
#shiro_redis_session=600000

#spring.zipkin.base-url=http://localhost:9411
