zuul:
  routes:
    ignored-services:  *
### 定义转发服务规则
	api-a:
###	当客户端发送的请求以 127.0.0.1:6000/api-login 开头的都会转发到登录服务 
	  path:/api-login/
### 服务别名 zuul网关默认整合了ribbon 自动实现负载均衡轮询效果	    
	  serviceId:  app-login-service
	api-b:
###	当客户端发送的请求以 127.0.0.1:6000/api-opendoor 开头的都会转发到开门服务 
	  path:/api-opendoor/
### 服务别名 zuul网关默认整合了ribbon 自动实现负载均衡轮询效果	    
	  serviceId:  app-openDoor-service  
	  
	  

  

