spring:
  profiles:
    active: dev

---
server: 
  port: 2003

spring:
  profiles: dev
  application:
    name: springcloud-service-consumer-config-clent

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka8003.com:8003/eureka/,http://eureka8002.com:8002/eureka/,http://eureka8001.com:8001/eureka/

---
server: 
  port: 2004

spring:
  profiles: test
  application:
    name: springcloud-service-consumer-config-clent

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka8003.com:8003/eureka/,http://eureka8002.com:8002/eureka/,http://eureka8001.com:8001/eureka/
